products:
  product1: 
    productName: "Sauce Labs Backpack"
    price: 29.99
  product2: 
    productName: "Sauce Labs Bike Light"
    price: 9.99
  product3: 
    productName: "Sauce Labs Bolt T-Shirt"
    price: 15.99
  product4: 
    productName: "Sauce Labs Fleece Jacket"
    price: 49.99